apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-data-vedtak
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  port: 8080
  prometheus:
    enabled: true
  replicas: # Custom HPA overstyrer
    min: 1
    max: 1
  strategy:
    type: Recreate
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka.pool}}
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{kafka.consumer_group_id}}
    - name: KAFKA_RAPID_TOPIC
      value: teamdagpenger.rapid.v1
    - name: KAFKA_RESET_POLICY
      value: earliest
    - name: DATA_PRODUKT_TOPIC
      value: teamdagpenger.{{ data.topic }}
