apiVersion: "kafka.nais.io/v1"
kind: "Topic"
metadata:
  name: {{ kafka.topic }}
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  pool: {{ kafka.pool }}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 72
  acl:
    - team: teamdagpenger
      application: dp-data-vedtak
      access: readwrite
    - team: teamdagpenger
      application: dp-kafka-connect
      access: read
    - team: teamdagpenger
      application: dp-data-admin
      access: readwrite
